name: CI-CD Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-application-artifacts"
  EB_APPLICATON_NAME        : "MyFlask"
  EB_ENVIRONEMT_NAME        : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-north-1"
  
on:
  push:
    branches:
      - main
      
jobs:      
      
  cd_part:
    runs-on: ubuntu-latest
    needs  : [ci_part]
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region           : ${{ env.AWS_REGION_NAME }}
        
        
    - name: Create New ElasticBeanStalk Application
      run : |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label "Ver-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"
        
    - name: Deploy New Elastic BeanStalk Application Version
      run : aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONEMT_NAME }} --version-label "Ver-${{ github.sha }}"
      
    - name: Print Message For CD Finish
      run : echo "CD Part Finished Successfully!"
    
        
